#!/bin/bash

sed -e '/broker_module=.*\/livestatus.so/s/^#//' \
    -e '/date_format=/c\date_format=iso8601' \
    -i.bak /etc/naemon/naemon.cfg

sed -e '/\$USER2\$/c\\$USER2\$=\/naemon\/plugins/' \
    -i.bak /etc/naemon/resource.cfg

install -d -m 0755 -o root -g root /naemon/plugins

if [[ ! -h /etc/naemon/conf.d ]]; then
    mv /etc/naemon/conf.d /etc/naemon/conf.d.orig
    ln -s /naemon/conf.d /etc/naemon/
fi
if [[ ! -e /naemon/conf.d ]]; then
    cp -r /etc/naemon/conf.d.orig /naemon/conf.d
fi

exec chpst -u naemon /usr/bin/naemon /etc/naemon/naemon.cfg
